In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("D:\\Home_credit\\raw_datasets\\application_train.csv")
df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
required_columns = [
    "SK_ID_CURR",
    "DAYS_BIRTH",
    "DAYS_EMPLOYED",
    "AMT_INCOME_TOTAL",
    "AMT_CREDIT",
    "AMT_ANNUITY",
    "AMT_GOODS_PRICE",
    "CNT_FAM_MEMBERS"
]
df[required_columns].head()

,SK_ID_CURR,DAYS_BIRTH,DAYS_EMPLOYED,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,CNT_FAM_MEMBERS
0,100002,-9461,-637,202500.0,406597.5,24700.5,351000.0,1.0
1,100003,-16765,-1188,270000.0,1293502.5,35698.5,1129500.0,2.0
2,100004,-19046,-225,67500.0,135000.0,6750.0,135000.0,1.0
3,100006,-19005,-3039,135000.0,312682.5,29686.5,297000.0,2.0
4,100007,-19932,-3038,121500.0,513000.0,21865.5,513000.0,1.0

In [5]:
df["AGE_YEARS"] = (-df["DAYS_BIRTH"] / 365.25).round(1)

C:\Users\Dell\AppData\Local\Temp\ipykernel_2232\836546203.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["AGE_YEARS"] = (-df["DAYS_BIRTH"] / 365.25).round(1)

In [6]:
df[["DAYS_BIRTH", "AGE_YEARS"]].head()

   DAYS_BIRTH  AGE_YEARS
0       -9461       25.9
1      -16765       45.9
2      -19046       52.1
3      -19005       52.0
4      -19932       54.6

In [7]:
df["AGE_YEARS"].describe()

count    307511.000000
mean         43.906968
std          11.947987
min          20.500000
25%          34.000000
50%          43.100000
75%          53.900000
max          69.100000
Name: AGE_YEARS, dtype: float64

In [8]:
df["EMPLOYMENT_YEARS"] = np.where(
    df["DAYS_EMPLOYED"] == 365243,
    np.nan,
    (-df["DAYS_EMPLOYED"] / 365.25).round(1)
)

C:\Users\Dell\AppData\Local\Temp\ipykernel_2232\419856965.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["EMPLOYMENT_YEARS"] = np.where(

In [9]:
df[["DAYS_EMPLOYED", "EMPLOYMENT_YEARS"]].head(10)

   DAYS_EMPLOYED  EMPLOYMENT_YEARS
0           -637               1.7
1          -1188               3.3
2           -225               0.6
3          -3039               8.3
4          -3038               8.3
5          -1588               4.3
6          -3130               8.6
7           -449               1.2
8         365243               NaN
9          -2019               5.5

In [10]:
df["EMPLOYMENT_YEARS"].describe()

count    252137.000000
mean          6.527443
std           6.402172
min           0.000000
25%           2.100000
50%           4.500000
75%           8.700000
max          49.000000
Name: EMPLOYMENT_YEARS, dtype: float64

In [11]:
df["EMPLOYMENT_YEARS"].isnull().sum()

np.int64(55374)

In [12]:
df["AGE_GROUP"] = pd.cut(
    df["AGE_YEARS"],
    bins=[0, 30, 40, 50, 60, np.inf],
    labels=["20–30", "31–40", "41–50", "51–60", "60+"],
    include_lowest=True
)

C:\Users\Dell\AppData\Local\Temp\ipykernel_2232\3469940526.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["AGE_GROUP"] = pd.cut(

In [13]:
df["AGE_GROUP"].value_counts().sort_index()

AGE_GROUP
20–30    45530
31–40    82413
41–50    76479
51–60    68080
60+      35009
Name: count, dtype: int64

In [14]:
df[["AGE_YEARS", "AGE_GROUP"]].head(10)

   AGE_YEARS AGE_GROUP
0       25.9     20–30
1       45.9     41–50
2       52.1     51–60
3       52.0     51–60
4       54.6     51–60
5       46.4     41–50
6       37.7     31–40
7       51.6     51–60
8       55.0     51–60
9       39.6     31–40

In [15]:
# Create EMPLOYMENT_GROUP
df["EMPLOYMENT_GROUP"] = pd.cut(
    df["EMPLOYMENT_YEARS"],
    bins=[-np.inf, 1, 3, 5, 10, 20, np.inf],
    labels=[
        "<1 Year",
        "1–3 Years",
        "3–5 Years",
        "5–10 Years",
        "10–20 Years",
        "20+ Years"
    ],
    right=False
)

df["EMPLOYMENT_GROUP"] = df["EMPLOYMENT_GROUP"].cat.add_categories(
    ["Unemployed / Special"]
)

df["EMPLOYMENT_GROUP"] = df["EMPLOYMENT_GROUP"].fillna(
    "Unemployed / Special"
)

C:\Users\Dell\AppData\Local\Temp\ipykernel_2232\1732099133.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["EMPLOYMENT_GROUP"] = pd.cut(

In [16]:
df["EMPLOYMENT_GROUP"].value_counts()

EMPLOYMENT_GROUP
5–10 Years              65436
1–3 Years               61704
Unemployed / Special    55374
3–5 Years               47271
10–20 Years             38719
<1 Year                 26366
20+ Years               12641
Name: count, dtype: int64

In [17]:
df[["EMPLOYMENT_YEARS", "EMPLOYMENT_GROUP"]].head(10)

   EMPLOYMENT_YEARS      EMPLOYMENT_GROUP
0               1.7             1–3 Years
1               3.3             3–5 Years
2               0.6               <1 Year
3               8.3            5–10 Years
4               8.3            5–10 Years
5               4.3             3–5 Years
6               8.6            5–10 Years
7               1.2             1–3 Years
8               NaN  Unemployed / Special
9               5.5            5–10 Years

In [18]:
df["INCOME_GROUP"] = pd.qcut(
    df["AMT_INCOME_TOTAL"],
    q=5,
    labels=["Very Low", "Low", "Middle", "High", "Very High"],
    duplicates="drop"
)

C:\Users\Dell\AppData\Local\Temp\ipykernel_2232\699487407.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["INCOME_GROUP"] = pd.qcut(

In [19]:
df["INCOME_GROUP"].value_counts().sort_index()

INCOME_GROUP
Very Low     63671
Low          85756
Middle       35453
High         75513
Very High    47118
Name: count, dtype: int64

In [20]:
df[["AMT_INCOME_TOTAL", "INCOME_GROUP"]].head(10)

   AMT_INCOME_TOTAL INCOME_GROUP
0          202500.0         High
1          270000.0    Very High
2           67500.0     Very Low
3          135000.0          Low
4          121500.0          Low
5           99000.0     Very Low
6          171000.0         High
7          360000.0    Very High
8          112500.0          Low
9          135000.0          Low

In [21]:
# Create Affordability Ratios
df["CREDIT_TO_INCOME"] = (
    df["AMT_CREDIT"] / df["AMT_INCOME_TOTAL"].replace(0, np.nan)
)

df["ANNUITY_TO_INCOME"] = (
    df["AMT_ANNUITY"] / df["AMT_INCOME_TOTAL"].replace(0, np.nan)
)

df["GOODS_TO_INCOME"] = (
    df["AMT_GOODS_PRICE"] / df["AMT_INCOME_TOTAL"].replace(0, np.nan)
)

df["CREDIT_TO_GOODS"] = (
    df["AMT_CREDIT"] / df["AMT_GOODS_PRICE"].replace(0, np.nan)
)

C:\Users\Dell\AppData\Local\Temp\ipykernel_2232\976905196.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["CREDIT_TO_INCOME"] = (
C:\Users\Dell\AppData\Local\Temp\ipykernel_2232\976905196.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["ANNUITY_TO_INCOME"] = (
C:\Users\Dell\AppData\Local\Temp\ipykernel_2232\976905196.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["GOODS_TO_INCOME"] = (
C:\Users\Dell\AppData\Local\Temp\ipykernel_2232\976905196.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["CREDIT_TO_GOODS"] = (

In [22]:
df[
    [
        "AMT_INCOME_TOTAL",
        "AMT_CREDIT",
        "AMT_ANNUITY",
        "AMT_GOODS_PRICE",
        "CREDIT_TO_INCOME",
        "ANNUITY_TO_INCOME",
        "GOODS_TO_INCOME",
        "CREDIT_TO_GOODS"
    ]
].head()

,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,CREDIT_TO_INCOME,ANNUITY_TO_INCOME,GOODS_TO_INCOME,CREDIT_TO_GOODS
0,202500.0,406597.5,24700.5,351000.0,2.007889,0.121978,1.733333,1.158397
1,270000.0,1293502.5,35698.5,1129500.0,4.790750,0.132217,4.183333,1.145199
2,67500.0,135000.0,6750.0,135000.0,2.000000,0.100000,2.000000,1.000000
3,135000.0,312682.5,29686.5,297000.0,2.316167,0.219900,2.200000,1.052803
4,121500.0,513000.0,21865.5,513000.0,4.222222,0.179963,4.222222,1.000000

In [23]:
df[
    [
        "CREDIT_TO_INCOME",
        "ANNUITY_TO_INCOME",
        "GOODS_TO_INCOME",
        "CREDIT_TO_GOODS"
    ]
].describe()

       CREDIT_TO_INCOME  ANNUITY_TO_INCOME  GOODS_TO_INCOME  CREDIT_TO_GOODS
count     307511.000000      307499.000000    307233.000000    307233.000000
mean           3.957570           0.180930         3.544322         1.122995
std            2.689728           0.094574         2.427708         0.124045
min            0.004808           0.000224         0.003885         0.150000
25%            2.018667           0.114782         1.840000         1.000000
50%            3.265067           0.162833         2.941176         1.118800
75%            5.159880           0.229067         4.615385         1.198000
max           84.736842           1.875965        84.736842         6.000000

In [24]:
df["INCOME_PER_FAMILY_MEMBER"] = (
    df["AMT_INCOME_TOTAL"] /
    df["CNT_FAM_MEMBERS"].replace(0, np.nan)
)

C:\Users\Dell\AppData\Local\Temp\ipykernel_2232\2992647926.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["INCOME_PER_FAMILY_MEMBER"] = (

In [25]:
df[
    [
        "AMT_INCOME_TOTAL",
        "CNT_FAM_MEMBERS",
        "INCOME_PER_FAMILY_MEMBER"
    ]
].head(10)

   AMT_INCOME_TOTAL  CNT_FAM_MEMBERS  INCOME_PER_FAMILY_MEMBER
0          202500.0              1.0                  202500.0
1          270000.0              2.0                  135000.0
2           67500.0              1.0                   67500.0
3          135000.0              2.0                   67500.0
4          121500.0              1.0                  121500.0
5           99000.0              2.0                   49500.0
6          171000.0              3.0                   57000.0
7          360000.0              2.0                  180000.0
8          112500.0              2.0                   56250.0
9          135000.0              1.0                  135000.0

In [26]:
df["INCOME_PER_FAMILY_MEMBER"].describe()

count    3.075090e+05
mean     9.310588e+04
std      1.013734e+05
min      2.812500e+03
25%      4.725000e+04
50%      7.500000e+04
75%      1.125000e+05
max      3.900000e+07
Name: INCOME_PER_FAMILY_MEMBER, dtype: float64

In [27]:
# verifying all engineered features
engineered_features = [
    "AGE_YEARS",
    "EMPLOYMENT_YEARS",
    "INCOME_GROUP",
    "AGE_GROUP",
    "EMPLOYMENT_GROUP",
    "CREDIT_TO_INCOME",
    "ANNUITY_TO_INCOME",
    "GOODS_TO_INCOME",
    "CREDIT_TO_GOODS",
    "INCOME_PER_FAMILY_MEMBER"
]

df[engineered_features].head()

,AGE_YEARS,EMPLOYMENT_YEARS,INCOME_GROUP,AGE_GROUP,EMPLOYMENT_GROUP,CREDIT_TO_INCOME,ANNUITY_TO_INCOME,GOODS_TO_INCOME,CREDIT_TO_GOODS,INCOME_PER_FAMILY_MEMBER
0,25.9,1.7,High,20–30,1–3 Years,2.007889,0.121978,1.733333,1.158397,202500.0
1,45.9,3.3,Very High,41–50,3–5 Years,4.790750,0.132217,4.183333,1.145199,135000.0
2,52.1,0.6,Very Low,51–60,<1 Year,2.000000,0.100000,2.000000,1.000000,67500.0
3,52.0,8.3,Low,51–60,5–10 Years,2.316167,0.219900,2.200000,1.052803,67500.0
4,54.6,8.3,Low,51–60,5–10 Years,4.222222,0.179963,4.222222,1.000000,121500.0

In [28]:
df[engineered_features].describe(include="all")

,AGE_YEARS,EMPLOYMENT_YEARS,INCOME_GROUP,AGE_GROUP,EMPLOYMENT_GROUP,CREDIT_TO_INCOME,ANNUITY_TO_INCOME,GOODS_TO_INCOME,CREDIT_TO_GOODS,INCOME_PER_FAMILY_MEMBER
count,307511.000000,252137.000000,307511,307511,307511,307511.000000,307499.000000,307233.000000,307233.000000,3.075090e+05
unique,NaN,NaN,5,5,7,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,Low,31–40,5–10 Years,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,85756,82413,65436,NaN,NaN,NaN,NaN,NaN
mean,43.906968,6.527443,NaN,NaN,NaN,3.957570,0.180930,3.544322,1.122995,9.310588e+04
std,11.947987,6.402172,NaN,NaN,NaN,2.689728,0.094574,2.427708,0.124045,1.013734e+05
min,20.500000,0.000000,NaN,NaN,NaN,0.004808,0.000224,0.003885,0.150000,2.812500e+03
25%,34.000000,2.100000,NaN,NaN,NaN,2.018667,0.114782,1.840000,1.000000,4.725000e+04
50%,43.100000,4.500000,NaN,NaN,NaN,3.265067,0.162833,2.941176,1.118800,7.500000e+04
75%,53.900000,8.700000,NaN,NaN,NaN,5.159880,0.229067,4.615385,1.198000,1.125000e+05
max,69.100000,49.000000,NaN,NaN,NaN,84.736842,1.875965,84.736842,6.000000,3.900000e+07

In [29]:
import os

os.makedirs(r"D:\Home_credit\processed_data", exist_ok=True)

df.to_csv(
    r"D:\Home_credit\processed_data\application_train_engineered.csv",
    index=False
)

print("Engineered dataset saved successfully.")

Engineered dataset saved successfully.

In [30]:
os.path.getsize(
    r"D:\Home_credit\processed_data\application_train_engineered.csv"
) / (1024 * 1024)

184.4786491394043